// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TedController from "./ted_controller"
import TtyController from "./tty_controller"
application.register("ted", TedController)
application.register("tty", TtyController)
